spring:
  application:
    name: search-service
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      group-id: search-service
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}

server:
  port: ${SERVER_PORT:8085}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  security:
    jwt-secret: ${JWT_SECRET:5d425331c66b17a28480fd38d2128e8350a24d535f23061c8d86bce66bdbcc44}
  clients:
    identity-url: ${IDENTITY_URL:http://localhost:8081}
    recruitment-url: ${RECRUITMENT_URL:http://localhost:8082}
    resume-url: ${RESUME_URL:http://localhost:8083}
    interaction-url: ${INTERACTION_URL:http://localhost:8084}
