spring:
  application:
    name: interaction-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/interaction_db}
    username: ${DB_USERNAME:interaction}
    password: ${DB_PASSWORD:interaction}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      group-id: interaction-service

server:
  port: ${SERVER_PORT:8088}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  security:
    jwt-secret: ${JWT_SECRET:5d425331c66b17a28480fd38d2128e8350a24d535f23061c8d86bce66bdbcc44}
    service-token: ${SERVICE_TOKEN:df0670418aa48ee9017ad05da2a1367b04e96686e5fb1bb0}
  clients:
    vacancy-url: ${VACANCY_URL:http://localhost:8084}
