services:
  application-db:
    image: postgres:17
    container_name: lab23-application-db
    environment:
      POSTGRES_DB: application_db
      POSTGRES_USER: application
      POSTGRES_PASSWORD: application
    ports:
      - "54327:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U application -d application_db"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - lab23-network

  application-service:
    build: .
    container_name: lab23-application-service
    entrypoint: ["java", "-Xms32m", "-Xmx256m", "-jar", "/app/app.jar"]
    environment:
      SERVER_PORT: 8087
      DB_URL: jdbc:postgresql://application-db:5432/application_db
      DB_USERNAME: application
      DB_PASSWORD: application
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_SECRET: 5d425331c66b17a28480fd38d2128e8350a24d535f23061c8d86bce66bdbcc44
      SERVICE_TOKEN: df0670418aa48ee9017ad05da2a1367b04e96686e5fb1bb0
      RESUME_URL: http://resume-service:8086
      VACANCY_URL: http://vacancy-service:8084
    depends_on:
      application-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "8087:8087"
    networks:
      - lab23-network

networks:
  lab23-network:
    name: lab23-network
