spring:
  application:
    name: lab1
  datasource:
    url: jdbc:postgresql://localhost:55432/job_search
    username: job_search
    password: job_search
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false

server:
  servlet:
    context-path: /api/v1
  tomcat:
    relaxed-query-chars: '[,]'

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: WARN

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  group-configs:
    - group: main-api
      paths-to-match: /**
      paths-to-exclude:
        - /industries/**
        - /experience-levels/**
        - /skills/**
    - group: dictionary-api
      paths-to-match:
        - /industries/**
        - /experience-levels/**
        - /skills/**

app:
  security:
    jwt:
      secret: change-me-change-me-change-me-change-me
      access-ttl-minutes: 120
