include:
  - ./platform/docker-compose.yml
  - ./auth-service/docker-compose.yml
  - ./user-service/docker-compose.yml
  - ./company-service/docker-compose.yml
  - ./vacancy-service/docker-compose.yml
  - ./search-service/docker-compose.yml
  - ./resume-service/docker-compose.yml
  - ./application-service/docker-compose.yml
  - ./interaction-service/docker-compose.yml
  - ./notification-service/docker-compose.yml
  - ./api-gateway/docker-compose.yml
