spring:
  application:
    name: notification-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/notification_db}
    username: ${DB_USERNAME:notification}
    password: ${DB_PASSWORD:notification}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      group-id: notification-service

server:
  port: ${SERVER_PORT:8089}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  security:
    jwt-secret: ${JWT_SECRET:5d425331c66b17a28480fd38d2128e8350a24d535f23061c8d86bce66bdbcc44}
  clients:
    identity-url: ${IDENTITY_URL:http://localhost:8081}
    resume-url: ${RESUME_URL:http://localhost:8086}
    interaction-url: ${INTERACTION_URL:http://localhost:8088}
